#
# File:    libc/Makefile
# Author:  Christoph Landgraf
# Purpose: Installs libc headers into /usr/include and invokes the Makefile 
#          in the source directory to compile libc and libk.
#

include ../config.mk
export INCLUDE_DIR=../img/usr/include/
include ../project.mk
