#
# File:    kernel/Makefile
# Author:  Christoph Landgraf
# Purpose: Installs kernel headers into /usr/include/kernel and invokes the Makefile 
#          in the source directory to compile libc and libk.
#

include ../config.mk
export INCLUDE_DIR=$(SYS_ROOT)/usr/include/kernel/
include ../project.mk
